### ISSUE TITLE
blogview CLIのWindows環境でのパス解決について

### ISSUE THREAD

**Issue by realteck-ky** [mkizka/blogview#5]
blogviewのCLIツールにおいてWindows環境で使用すると、正しくentryを作っていてもプレビューのページ `http://localhost:8000` が `Cannot GET /` を返すという現象に遭遇しました。
同様に `blogview -v` が `pkg.version` を拾えないという問題が発生していることもわかり、勝手ながら問題調査をしました。

結論としてファイルパスの解決に問題があり、現在のコードだとWindowsの場合、先頭が `/C:` などで始まってしまい不正なパスとなっているようでした。
解決策としては現在はurlモジュールの `fileURLToPath()` を使って変換をすることが推奨のようです。
https://github.com/nodejs/node/issues/28114

Linuxでの動作確認はしてないので、あくまで当方ではWindows上のみの動作確認となるのですが、よければ以下の修正を取り込んでいただければと思います。
[0001-Change-to-get-filepath-using-fileURLToPath.patch](https://github.com/mkizka/blogview/files/12564324/0001-Change-to-get-filepath-using-fileURLToPath.patch)

```diff
diff --git a/packages/blogview/src/server/utils/helper.ts b/packages/blogview/src/server/utils/helper.ts
index e35ca56..265c2d7 100644
--- a/packages/blogview/src/server/utils/helper.ts
+++ b/packages/blogview/src/server/utils/helper.ts
@@ -1,5 +1,6 @@
 import fs from "fs";
 import path from "path";
+import { fileURLToPath } from 'node:url';
 
 export function loadJson(filepath: string) {
   try {
@@ -10,7 +11,7 @@ export function loadJson(filepath: string) {
   }
 }
 
-const dirname = path.dirname(new URL(import.meta.url).pathname);
+const dirname = path.dirname(fileURLToPath(import.meta.url));
 
 const pkgRootDir = path.join(dirname, "..", "..", "..");
 ```

**Comment by mkizka** [comment]
こちら https://github.com/mkizka/blogview/commit/be87f5b4d1349672be6fdd3437837bbcbb7fc48f で取り込みました！ありがとうございます
